runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /
    static_files: dist/[shopforhome]/index.html
    upload: dist/[shopforhome]/index.html
  - url: /
    static_dir: dist/[shopforhome]
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE